"""Domain models — core value objects for the ALPHAFOUNDRY platform.

All models are immutable (frozen Pydantic v2 models).  UUIDs are generated by
the caller; the models never auto-generate IDs so that tests can pass explicit
values and remain deterministic.

Timestamps are always timezone-aware UTC.  The Decimal type is used for prices
and quantities that require exact arithmetic; float is acceptable only for
derived statistical values (scores, ratios, etc.).
"""

from .enums import (
    BenchmarkType,
    Direction,
    InstrumentType,
    OrderStatus,
    OrderType,
    RegimeType,
    SessionStatus,
    SessionType,
    Side,
    TradeSide,
    Urgency,
)
from .instruments import Instrument, Venue
from .market_data import OHLCBar, Quote, Trade
from .orders import ChildOrder, Fill, ParentOrder
from .research import (
    AnomalyReport,
    Explanation,
    FeatureLineageItem,
    FeatureVector,
    InstrumentRank,
    RegimeState,
    SessionSummary,
    Signal,
)
from .risk import PositionLimit, RiskConfig, RiskDecision, RuleViolation
from .sessions import Session
from .tca import TCAReport

__all__ = [
    # enums
    "BenchmarkType",
    "Direction",
    "InstrumentType",
    "OrderStatus",
    "OrderType",
    "RegimeType",
    "SessionStatus",
    "SessionType",
    "Side",
    "TradeSide",
    "Urgency",
    # market structure
    "Instrument",
    "Session",
    "Venue",
    # market data
    "OHLCBar",
    "Quote",
    "Trade",
    # analytics
    "FeatureLineageItem",
    "FeatureVector",
    "Signal",
    "InstrumentRank",
    "RegimeState",
    # orders
    "ChildOrder",
    "Fill",
    "ParentOrder",
    # risk
    "PositionLimit",
    "RiskConfig",
    "RiskDecision",
    "RuleViolation",
    # TCA
    "TCAReport",
    # AI / research
    "AnomalyReport",
    "Explanation",
    "SessionSummary",
]
