"""SyntheticAdapter — deterministic market-data generator.

Guarantees
----------
- Identical ``seed`` + ``SyntheticAdapterConfig`` → identical output every run.
- No external network calls; no licensed data.
- Produces plausible INR-denominated equity-like data suitable for
  testing the full pipeline in later phases.

Generation model
----------------
Daily OHLC bars use a geometric Brownian motion (GBM) random walk:

    price[t] = price[t-1] * exp(μ_dt + σ_dt * z)

where
    z          ~ N(0, 1)  — drawn from a seeded numpy.random.default_rng
    μ_dt       = 0        (zero drift; research-neutral)
    σ_dt       = annual_vol / sqrt(252)

Intra-day quotes are generated by subdividing a daily range into equal
time steps, interpolating price linearly, and perturbing with a much
smaller intra-day noise term (σ_dt / sqrt(bars_per_day)).

Volume per bar is Poisson-distributed around ``avg_volume``; this keeps
total daily volume realistic while staying deterministic under the seed.

Spread is a fixed fraction of the mid-price (``spread_fraction``).

The seed and full config are recorded on the adapter instance so any
caller can reproduce the exact sequence.
"""

from __future__ import annotations

import math
import random  # stdlib — used only for Poisson approximation (no numpy dep yet)
import uuid
from collections.abc import AsyncIterator
from datetime import UTC, datetime, timedelta
from decimal import Decimal
from uuid import UUID

from alphafoundry.adapters import IMarketDataAdapter
from alphafoundry.config import SyntheticAdapterConfig
from alphafoundry.domain import OHLCBar, Quote, Trade
from alphafoundry.domain.enums import InstrumentType, SessionStatus, TradeSide
from alphafoundry.domain.instruments import Instrument, Venue

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_VENUE_ID = "NSE_EQ"
_CURRENCY = "INR"
_LOT_SIZE = 1
_TICK_SIZE = Decimal("0.05")

# NSE Normal session (IST = UTC+5:30): 09:15 – 15:30
_SESSION_OPEN_H, _SESSION_OPEN_M = 9, 15
_SESSION_CLOSE_H, _SESSION_CLOSE_M = 15, 30

# Synthetic instrument universe — symbols only; ISINs are placeholders.
_INSTRUMENT_SPECS: list[tuple[str, str]] = [
    ("ALPHA", "INE000A01036"),
    ("BETA", "INE001A01036"),
    ("GAMMA", "INE002A01036"),
    ("DELTA", "INE003A01036"),
    ("EPSILON", "INE004A01036"),
]

_INTERVAL_MINUTES: dict[str, int] = {
    "1m": 1,
    "5m": 5,
    "15m": 15,
    "30m": 30,
    "1h": 60,
    "1d": 390,  # full trading day in minutes (09:15–15:30)
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _round_to_tick(price: float, tick: float = 0.05) -> Decimal:
    """Round *price* to the nearest tick and return as Decimal."""
    rounded = round(round(price / tick) * tick, 4)
    return Decimal(str(rounded))


def _poisson_sample(rng: random.Random, lam: float) -> int:
    """Knuth Poisson sampler — pure stdlib, deterministic under rng."""
    l_val = math.exp(-lam)
    k, p = 0, 1.0
    while p > l_val:
        k += 1
        p *= rng.random()
    return max(1, k - 1)


def _gauss(rng: random.Random) -> float:
    """Return a standard-normal sample using Box-Muller (stdlib)."""
    u1, u2 = rng.random(), rng.random()
    # Ensure u1 > 0 to avoid log(0).
    u1 = max(u1, 1e-15)
    return math.sqrt(-2.0 * math.log(u1)) * math.cos(2.0 * math.pi * u2)


# ---------------------------------------------------------------------------
# SyntheticAdapter
# ---------------------------------------------------------------------------


class SyntheticAdapter(IMarketDataAdapter):
    """Deterministic, seed-driven market-data generator."""

    def __init__(self, cfg: SyntheticAdapterConfig | None = None) -> None:
        self.cfg: SyntheticAdapterConfig = cfg or SyntheticAdapterConfig()
        self._rng = random.Random(self.cfg.seed)  # seeded once; never re-seeded

        self._venue = Venue(venue_id=_VENUE_ID, name="NSE (Synthetic)", timezone="Asia/Kolkata")
        self._instruments: list[Instrument] = [
            Instrument(
                instrument_id=self._stable_uuid(sym),
                isin=isin,
                symbol=sym,
                venue_id=_VENUE_ID,
                instrument_type=InstrumentType.EQ,
                lot_size=_LOT_SIZE,
                tick_size=_TICK_SIZE,
                currency=_CURRENCY,
                is_active=True,
            )
            for sym, isin in _INSTRUMENT_SPECS
        ]

        # Pre-generate all daily bars eagerly so get_ohlc and stream_quotes
        # both draw from the exact same price path.
        self._daily_bars: dict[UUID, list[OHLCBar]] = self._generate_all_daily_bars()

    # ------------------------------------------------------------------
    # IMarketDataAdapter interface
    # ------------------------------------------------------------------

    def get_instruments(self) -> list[Instrument]:
        return list(self._instruments)

    def get_ohlc(
        self,
        instrument_id: UUID,
        from_dt: datetime,
        to_dt: datetime,
        freq: str,
    ) -> list[OHLCBar]:
        """Return OHLC bars for *instrument_id* in [from_dt, to_dt] at *freq*.

        Only '1d' is fully pre-generated.  Intra-day frequencies are derived
        by subdividing the daily range.  Frequencies not in ``_INTERVAL_MINUTES``
        raise ValueError.
        """
        if freq not in _INTERVAL_MINUTES:
            raise ValueError(f"Unsupported freq '{freq}'. Supported: {list(_INTERVAL_MINUTES)}")

        daily = self._daily_bars.get(instrument_id, [])
        # Filter to requested window
        in_window = [b for b in daily if from_dt <= b.bar_open <= to_dt]

        if freq == "1d":
            return in_window

        # Intra-day: subdivide each daily bar
        interval_min = _INTERVAL_MINUTES[freq]
        result: list[OHLCBar] = []
        for day_bar in in_window:
            result.extend(self._subdivide_daily(day_bar, interval_min))
        return result

    async def stream_quotes(self) -> AsyncIterator[Quote]:
        """Yield 1-minute quotes for all instruments, day by day."""
        for instr in self._instruments:
            for bar in self._daily_bars[instr.instrument_id]:
                for q in self._quotes_from_bar(instr, bar):
                    yield q

    async def stream_trades(self) -> AsyncIterator[Trade]:
        """Yield one synthetic trade per intra-day bar for all instruments."""
        for instr in self._instruments:
            for bar in self._daily_bars[instr.instrument_id]:
                for minute_bar in self._subdivide_daily(bar, interval_min=1):
                    yield self._trade_from_bar(instr, minute_bar)

    # ------------------------------------------------------------------
    # Generation internals
    # ------------------------------------------------------------------

    def _stable_uuid(self, seed_str: str) -> UUID:
        """Return a deterministic UUID5 from a string namespace."""
        return uuid.uuid5(uuid.NAMESPACE_OID, f"alphafoundry.synthetic.{seed_str}")

    def _generate_all_daily_bars(self) -> dict[UUID, list[OHLCBar]]:
        """Generate ``num_days`` daily bars for every instrument.

        Each instrument gets its own sub-RNG state to ensure independence:
        we burn a fixed number of draws before each instrument so re-ordering
        the instrument list doesn't perturb others.
        """
        sigma_daily = self.cfg.annual_vol / math.sqrt(252)
        start_date = datetime(2023, 1, 2, tzinfo=UTC)  # first synthetic trading day

        result: dict[UUID, list[OHLCBar]] = {}
        for instr in self._instruments:
            price = self.cfg.base_price
            bars: list[OHLCBar] = []
            seq = 0
            day_offset = 0
            days_generated = 0
            while days_generated < self.cfg.num_days:
                bar_date = start_date + timedelta(days=day_offset)
                # Skip weekends (Mon=0 … Fri=4)
                if bar_date.weekday() >= 5:
                    day_offset += 1
                    continue

                open_price = price
                z = _gauss(self._rng)
                daily_return = math.exp(sigma_daily * z)
                close_price = open_price * daily_return

                high_price = max(open_price, close_price) * (1 + abs(_gauss(self._rng)) * 0.005)
                low_price = min(open_price, close_price) * (1 - abs(_gauss(self._rng)) * 0.005)
                volume = _poisson_sample(self._rng, float(self.cfg.avg_volume))
                num_trades = _poisson_sample(self._rng, 500.0)
                vwap = (open_price + high_price + low_price + close_price) / 4.0

                open_dec = _round_to_tick(open_price)
                close_dec = _round_to_tick(close_price)
                raw_high_dec = _round_to_tick(high_price)
                raw_low_dec = _round_to_tick(low_price)

                high_dec = max(open_dec, close_dec, raw_high_dec)
                low_dec = min(open_dec, close_dec, raw_low_dec)

                bar_open_dt = bar_date.replace(
                    hour=_SESSION_OPEN_H, minute=_SESSION_OPEN_M, second=0, microsecond=0
                )
                bar_close_dt = bar_date.replace(
                    hour=_SESSION_CLOSE_H, minute=_SESSION_CLOSE_M, second=0, microsecond=0
                )

                bars.append(
                    OHLCBar(
                        instrument_id=instr.instrument_id,
                        venue_id=_VENUE_ID,
                        freq="1d",
                        bar_open=bar_open_dt,
                        bar_close=bar_close_dt,
                        open=open_dec,
                        high=high_dec,
                        low=low_dec,
                        close=close_dec,
                        volume=volume,
                        num_trades=num_trades,
                        vwap=_round_to_tick(vwap),
                        is_complete=True,
                    )
                )
                price = close_price
                seq += 1
                day_offset += 1
                days_generated += 1

            result[instr.instrument_id] = bars
        return result

    def _subdivide_daily(self, day_bar: OHLCBar, interval_min: int) -> list[OHLCBar]:
        """Split a daily bar into intra-day bars of *interval_min* minutes.

        Price path: linear interpolation between open and close, with a tiny
        intra-day noise term.  Volume is distributed proportionally.
        """
        session_minutes = 375  # NSE: 09:15 – 15:30
        n_bars = session_minutes // interval_min
        if n_bars == 0:
            return [day_bar]

        open_f = float(day_bar.open)
        volume_per = max(1, day_bar.volume // n_bars)
        intraday_sigma = (self.cfg.annual_vol / math.sqrt(252)) / math.sqrt(
            session_minutes / interval_min
        )

        bars: list[OHLCBar] = []
        current_price = open_f

        for i in range(n_bars):
            bar_open_dt = day_bar.bar_open + timedelta(minutes=i * interval_min)
            bar_close_dt = bar_open_dt + timedelta(minutes=interval_min)

            z = _gauss(self._rng)
            next_price = current_price * math.exp(intraday_sigma * z)
            b_open_raw = current_price
            b_close_raw = next_price
            b_high_raw = max(b_open_raw, b_close_raw) * (1 + abs(_gauss(self._rng)) * 0.001)
            b_low_raw = min(b_open_raw, b_close_raw) * (1 - abs(_gauss(self._rng)) * 0.001)

            b_open = _round_to_tick(b_open_raw)
            b_close = _round_to_tick(b_close_raw)
            b_high = max(b_open, b_close, _round_to_tick(b_high_raw))
            b_low = min(b_open, b_close, _round_to_tick(b_low_raw))

            bars.append(
                OHLCBar(
                    instrument_id=day_bar.instrument_id,
                    venue_id=day_bar.venue_id,
                    freq=f"{interval_min}m",
                    bar_open=bar_open_dt,
                    bar_close=bar_close_dt,
                    open=b_open,
                    high=b_high,
                    low=b_low,
                    close=b_close,
                    volume=volume_per,
                    num_trades=max(1, volume_per // 20),
                    vwap=_round_to_tick(
                        (float(b_open) + float(b_high) + float(b_low) + float(b_close)) / 4.0
                    ),
                    is_complete=(i < n_bars - 1),
                )
            )
            current_price = next_price

        return bars

    def _quotes_from_bar(self, instr: Instrument, day_bar: OHLCBar) -> list[Quote]:
        """Generate 1-minute quotes for one daily bar."""
        minute_bars = self._subdivide_daily(day_bar, interval_min=1)
        quotes: list[Quote] = []
        for i, mb in enumerate(minute_bars):
            mid = float(mb.close)
            half_spread = max(0.05, mid * self.cfg.spread_fraction / 2)
            bid = _round_to_tick(mid - half_spread)
            ask = _round_to_tick(mid + half_spread)
            if ask <= bid:
                ask = bid + _TICK_SIZE

            ts = mb.bar_close
            seq = int(ts.timestamp() * 1000) % (2**31)  # surrogate sequence id
            idem_key = f"{_VENUE_ID}:{instr.instrument_id}:{i}:{day_bar.bar_open.date()}"

            quotes.append(
                Quote(
                    idempotency_key=idem_key,
                    instrument_id=instr.instrument_id,
                    venue_id=_VENUE_ID,
                    timestamp=ts,
                    received_at=ts,
                    sequence_id=seq,
                    bid_price=bid,
                    bid_qty=_poisson_sample(self._rng, 500),
                    ask_price=ask,
                    ask_qty=_poisson_sample(self._rng, 500),
                    last_trade_price=mb.close,
                    session_status=SessionStatus.OPEN,
                    is_stale=False,
                )
            )
        return quotes

    def _trade_from_bar(self, instr: Instrument, bar: OHLCBar) -> Trade:
        """Generate one synthetic trade for a bar."""
        side = TradeSide.BUY if self._rng.random() > 0.5 else TradeSide.SELL
        seq = int(bar.bar_close.timestamp() * 1000) % (2**31)
        idem_key = f"{_VENUE_ID}:trade:{instr.instrument_id}:{bar.bar_open}"
        return Trade(
            idempotency_key=idem_key,
            instrument_id=instr.instrument_id,
            venue_id=_VENUE_ID,
            timestamp=bar.bar_close,
            received_at=bar.bar_close,
            sequence_id=seq,
            price=bar.close,
            qty=max(1, bar.volume // bar.num_trades) if bar.num_trades else 1,
            side=side,
        )
